name: Build image and deploy to Dockerhub registry

on:
  push:
    branches: [main]

jobs:
  create_and_deploy_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and deploy image
        run: >
          ./gradlew jib --image=rafagomezp/tt-sant-andreu
          -Djib.to.auth.username=${{ secrets.DOCKERHUB_USER }}
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_PWD }}

  deploy_to_digital_ocean:
    runs-on: ubuntu-latest
    needs: [create_and_deploy_image]
    steps:
      - name: Install sshpass
        run: sudo apt-get -y install sshpass

      - name: Get into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          debug: true
          script: |
            container_id=$(docker ps -aqf "ancestor=rafagomezp/tt-sant-andreu")
            echo "Container ID: $container_id"
            docker stop $container_id
            docker rm $container_id
            docker pull rafagomezp/tt-sant-andreu
            docker run -d -p 8080:8080 rafagomezp/tt-sant-andreu
