name: Build image and deploy to Dockerhub registry

on:
  push:
    branches: [main]

jobs:
  create-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  deploy-to-digital-ocean:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy image
        run: >
          ./gradlew jib --image=rafagomezp/tt-sant-andreu
          -Djib.to.auth.username=${{ secrets.DOCKERHUB_USER }}
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_PWD }}

      - name: Get into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}

      - name: Copy Docker image to Droplet
        run: docker save rafagomezp/tt-sant-andreu | sshpass -p ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }} ssh ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}@${{ secrets.DIGITALOCEAN_DROPLET_IP }} docker load

      - name: Run Docker container on Droplet
        run: sshpass -p ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }} ssh ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}@${{ secrets.DIGITALOCEAN_DROPLET_IP }} docker run -d -p 8080:8080 rafagomezp/tt-sant-andreu